### PR TITLE
Subscription updates and maintenance

### PR DESCRIPTION
**Pull request by lynch16**

### CODE REVIEW

**Review by jessebobrien — COMMENTED** [review]
Are the binary gems available elsewhere, so they wouldn't need to be tracked in the repository?

**Comment by lynch16** [comment]
Why wouldn't we want github to track the gems?

**Comment by jessebobrien** [comment]
We don't get usable diffs, and they're more difficult to test in an automated fashion.

**Comment by lynch16** [comment]
I don't think I understand what you're referring to.  Are you talking about the Gemfile.lock?

**Comment by lynch16** [comment]
Or the cache?

**Comment by jessebobrien** [comment]
/vendor/cache - yes. They aren't massive files, but it seems like they could be in the .gitignore.

**Comment by lynch16** [comment]
Yea for sure.  They're only included because Heroku was blowing up when I didn't include them.  They can all be fetched from the Gemfile.  They can be removed as soon as I have time to sort out the Heroku issue.

**Pull request merged**
